### ISSUE TITLE
GPSD socket streaming possible?

### ISSUE THREAD

**Issue by Calimerorulez** [semuconsulting/pynmeagps#7]
Hi,

I came across your project, and I would like to know if it is possible to use it with GPSD? I'm using GPSD to feed my NTP-server, and I would like to parse GPSD's output on port 2947, instead of using serial input.

But I'm just learning Python, so please bear with me :)

Thanks

**Comment by semuadmin** [comment]
Hi. I'm afraid the simple answer is 'No'. As I understand it, gpsd essentially parses the generic NMEA0183 output from a GPS device to a TCP/IP stream in a bespoke JSON format, so its output would be unrecognisable to pynmeagps (_even assuming the latter could communicate via TCP_). You could if you wanted write a Python TCP wrapper around pynmeagps if your objective is to monitor GPS output via TCP/IP rather than serial, but you'd effectively be replicating what gpsd already does.

**Comment by semuadmin** [comment]
Just an afterthought... This won't help you with your gpsd integration problem, but for what it's worth I've uploaded a very simple HTTP web server wrapper example that I was messing around with a while back which illlustrates how you might go about streaming the parsed output from pynmeagps over TCP/IP (in this case to a dynamically updated web page via a REST API). This might provide some general pointers - it's in the /examples/webserver folder.
